version: '3.8'

services:
  backend:
    build:
      context: ./definance-backend/definance-backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AWS_REGION=us-east-2
      - S3_BUCKET_NAME=definance-avatars
      - IA_SERVICE_URL=http://ia-service:8000
    container_name: definance_api
    restart: always
    networks:
      - definance-net
    depends_on:
      - ia-service

  ia-service:
    build:
      context: ./definance-ia
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AWS_REGION=us-east-2
      - S3_BUCKET_NAME=definance-avatars
    container_name: definance_ia
    restart: always
    networks:
      - definance-net

networks:
  definance-net:
    driver: bridge
